# Generated by Django 4.2.7 on 2024-02-01 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(default='', max_length=2)),
                ('countryName', models.CharField(default='', max_length=100)),
                ('currencyCode', models.CharField(blank=True, max_length=3, null=True)),
                ('telephonePrefix', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_users',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.country')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc_name', models.CharField(blank=True, max_length=155, null=True)),
                ('poc_phone', models.CharField(blank=True, max_length=155, null=True)),
                ('poc_email', models.EmailField(blank=True, max_length=155, null=True)),
                ('flat_no', models.CharField(max_length=155)),
                ('house_no', models.CharField(max_length=155)),
                ('landmark', models.CharField(max_length=155)),
                ('postal_code', models.CharField(max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('address_type', models.CharField(max_length=155)),
                ('address_line1', models.CharField(max_length=155)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.country')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='customer.customer')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
